### ISSUE TITLE
development of version 2

### ISSUE THREAD

**Issue by henil0604** [henil0604/ssip-2023#1]
# TODO

- [x] User account management system
- [x] User can create their personal replacer database
- [ ] Analytics of user feedback and response
- [ ] Save the theme selected by user
- [ ] Grammarly Support
- [x] Caching system

## Translator
- [x] Support All Languages like Google translate
- [x] Users can edit/make little changes and save the translated output.
- [x] Interchange Languages through button
- [ ] URL Input Support
- [x] Text to Speech Support

## Question Generator

- [x] User can adjust Difficulty level of questions generated.
- [x] User can adjust Format of the questions generated.

## Solution Generator

- [ ] User can Select subject
- [ ] User can Select domain
- [x] OpenAI ChatGPT Chatbot

**Comment by henil0604** [comment]
Core translation module (Frontend + Backend) working at this point (f616626226aefe498a6e685d492cdf0bc3fe7f7c)
